import {randomUUID, randomInt} from 'node:crypto';
import {CARDS, CLASSES, RELICS, ENEMIES, TOTAL_FLOORS, priceOf} from './data.js';
export {CARDS, CLASSES, RELICS, TOTAL_FLOORS};
const shuffle = items => {const a=[...items];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
const has=(p,key)=>p.relics.includes(key);
const stats=()=>({strength:0,dexterity:0,thorns:0,regen:0,dodge:0,soul:0,weak:0,vulnerable:0,channel:0,soulFlow:0,plating:0});
export function player(name,classId){if(!Object.hasOwn(CLASSES,classId))throw Error('직업을 선택해주세요.');const c=CLASSES[classId];return {id:randomUUID(),name:String(name||'순례자').trim().slice(0,16)||'순례자',classId,hp:c.hp,maxHp:c.hp,gold:90,deck:['strike','strike','strike','guard','guard','guard',...c.starter],relics:[],ready:false,ended:false,lastSeen:Date.now(),block:0,status:stats(),metrics:{damage:0,healed:0,cards:0},done:false};}
export function room(code,publicQueue=false){return {code,publicQueue,phase:'lobby',floor:0,players:[],host:null,log:['안식처를 향한 여정이 시작됩니다.'],events:[],eventSeq:0,history:[],created:Date.now(),updated:Date.now(),totalFloors:TOTAL_FLOORS};}
function say(r,s){r.log=[...r.log,s].slice(-16);}
function emit(r,e){r.events.push({...e,id:++r.eventSeq,time:Date.now()});r.events=r.events.slice(-48);}
function heal(p,n){if(p.hp<=0)return 0;const actual=Math.min(p.maxHp-p.hp,Math.max(0,n));p.hp+=actual;p.metrics.healed+=actual;return actual;}
function draw(p,n){for(let i=0;i<n&&p.hand.length<12;i++){if(!p.pile.length){p.pile=shuffle(p.discard);p.discard=[];}if(!p.pile.length)break;p.hand.push(p.pile.pop());}}
function pool(p){return Object.keys(CARDS).filter(id=>!CARDS[id].upgraded&&!['strike','guard'].includes(id)&&['neutral',p.classId].includes(CARDS[id].classId));}
function offers(p,count){return shuffle(pool(p)).slice(0,count);}
function gainBlock(p,n){if(p.hp<=0)return 0;const amount=n+p.status.dexterity;p.block+=amount;return amount;}
function rawDamage(e,n){const amount=Math.min(e.hp,Math.max(0,Math.floor(n)));e.hp-=amount;return amount;}
function hitEnemy(e,n){const blocked=Math.min(e.block,n);e.block-=blocked;return rawDamage(e,n-blocked);}
export function preview(r,p,id){const c=CARDS[id];if(!c)return null;let dmg=c.damage||0;const e=r.enemy;
 if(dmg&&e){dmg+=p.status.strength+(p.classId==='warrior'?2:0)+(c.soulBonus||0)*p.status.soul+(c.burnBonus||0)*e.status.burn+(c.bleedBonus||0)*e.status.bleed+Math.floor((c.blockBonus||0)*p.block);if(c.comboBonus&&p.played>=2)dmg+=c.comboBonus;if(c.execute&&e.hp/e.maxHp<=.4)dmg+=c.execute;if(c.allEnergy)dmg+=Math.max(0,p.energy-c.cost)*c.allEnergy;if(p.status.weak)dmg=Math.floor(dmg*.75);if(e.status.vulnerable)dmg=Math.floor(dmg*1.5);}
 return {damage:dmg,hits:c.hits||1,block:c.block?c.block+p.status.dexterity:0,heal:(c.heal||0)+(c.soulHeal||0)*p.status.soul,combo:!!(c.comboBonus&&p.played>=2),cost:c.cost};
}
function refreshEnemy(r){const e=r.enemy;if(e.boss&&!e.enraged&&e.hp/e.maxHp<=.5){e.enraged=true;e.fury+=3;say(r,'망각의 왕이 두 번째 형상으로 깨어납니다. 공격력 +3.');emit(r,{type:'enrage',fx:'soul',label:'망각의 왕 · 두 번째 형상'});}const n=6+Math.floor(r.floor*.7)+e.fury;const intent=e.intent;e.hits=intent==='multi'?2:['attack','heavy'].includes(intent)?1:0;let attack=intent==='heavy'?n+4:intent==='multi'?Math.ceil(n*.65):n;attack=Math.max(0,attack-e.status.frost);if(e.status.weak)attack=Math.floor(attack*.75);e.attack=e.hits?attack:0;e.intentLabel={attack:'영혼 할퀴기',heavy:'파멸의 일격',multi:'연속 습격',ward:'망령의 장벽',curse:'쇠약의 저주',charge:'어둠 축적'}[intent];}
function newTurn(r){r.turn++;const e=r.enemy;e.intent=ENEMIES[e.kind].pattern[(r.turn-1)%ENEMIES[e.kind].pattern.length];for(const p of r.players){p.discard.push(...p.hand);p.hand=[];p.block=(p.retainBlock?p.block:0)+(p.classId==='knight'?4:0)+p.status.plating+(has(p,'shell')?3:0);p.retainBlock=false;p.energy=Math.min(10,(p.classId==='mage'?4:3)+p.status.channel+(r.turn===1&&has(p,'hourglass')?1:0));p.played=0;p.ended=p.hp<=0;if(p.status.regen){heal(p,p.status.regen);p.status.regen--;}p.status.soul+=p.status.soulFlow;if(p.hp>0)draw(p,(p.classId==='rogue'?6:5)+(has(p,'lens')?1:0));}refreshEnemy(r);emit(r,{type:'turn',label:`TURN ${r.turn}`,fx:'aura'});}
function battle(r,elite=false,boss=false){r.phase='battle';const kind=boss?'boss':elite?'executioner':['hound','wraith','sentinel'][(r.floor-1)%3];const base=boss?145:elite?70:38;const hp=(base+r.floor*(boss?6:5))*r.players.length;r.enemy={...ENEMIES[kind],kind,hp,maxHp:hp,block:0,boss,elite,fury:0,enraged:false,status:{poison:0,burn:0,bleed:0,weak:0,vulnerable:0,frost:0}};r.turn=0;for(const p of r.players){p.status=stats();p.status.strength=has(p,'ember')?1:0;p.pile=shuffle(p.deck);p.hand=[];p.discard=[];p.exhaust=[];p.retainBlock=false;}newTurn(r);say(r,`${r.enemy.name}이 길을 막습니다.`);}
function win(r){for(const p of r.players){p.rewardGold=(r.enemy.elite?45:30)+(has(p,'coin')?12:0);p.gold+=p.rewardGold;if(p.hp<=0)p.hp=Math.ceil(p.maxHp*.25);heal(p,(p.classId==='reaper'?7:0)+(has(p,'dew')?5:0));p.offers=offers(p,3);p.done=false;if(r.enemy.elite){const relic=shuffle(Object.keys(RELICS).filter(key=>!has(p,key)))[0];if(relic){p.relics.push(relic);p.rewardRelic=relic;}else p.rewardRelic=null;}else p.rewardRelic=null;}r.phase=r.enemy.boss?'victory':'reward';say(r,'전투 승리! 흩어진 기억을 회수했습니다.');emit(r,{type:'victory',fx:'holy',label:r.enemy.boss?'영혼의 쉼터에 도착했습니다':'전투 승리'});}
function resolve(r){const e=r.enemy;
 for(const kind of ['poison','burn',...(e.hits?['bleed']:[])])if(e.status[kind]){const damage=rawDamage(e,e.status[kind]);emit(r,{type:'dot',fx:kind==='burn'?'fire':kind==='bleed'?'blood':'poison',damage,label:kind});e.status[kind]=kind==='burn'?Math.floor(e.status[kind]/2):e.status[kind]-1;}
 if(e.hp<=0){win(r);return;}e.block=0;
 const received=[];for(const p of r.players){if(p.hp<=0)continue;let damage=0,blocked=0,dodged=0;for(let i=0;i<e.hits;i++){if(p.status.dodge){p.status.dodge--;dodged++;continue;}const n=Math.floor(e.attack*(p.status.vulnerable?1.5:1));const b=Math.min(p.block,n);p.block-=b;blocked+=b;const taken=Math.min(p.hp,n-b);p.hp-=taken;damage+=taken;if(p.status.thorns)rawDamage(e,p.status.thorns);if(p.hp<=0)break;}received.push({actor:p.id,damage,blocked,dodged});for(const key of ['weak','vulnerable'])p.status[key]=Math.max(0,p.status[key]-1);}
 if(e.intent==='charge'){e.fury+=3;say(r,'적이 어둠을 축적했습니다. 이후 공격력 +3.');}
 if(e.intent==='ward'){e.block=(10+r.floor)*r.players.length;say(r,`적이 방어도 ${e.block}을 얻었습니다.`);}
 if(e.intent==='curse'){for(const p of r.players)if(p.hp>0){p.status.weak+=2;p.status.vulnerable+=1;}say(r,'쇠약의 저주! 아군 약화 2, 취약 1.');}
 if(e.hits)say(r,`${e.name} · ${e.attack} × ${e.hits} 전원 공격`);
 emit(r,{type:'enemy',fx:e.hits?'slash':e.intent==='curse'?'soul':'aura',targets:received,label:e.intentLabel});
 for(const key of ['weak','vulnerable'])e.status[key]=Math.max(0,e.status[key]-1);e.status.frost=0;
 if(r.players.every(p=>p.hp<=0)){r.phase='defeat';emit(r,{type:'defeat',fx:'soul',label:'다시 만날 그날까지'});return;}if(e.hp<=0){win(r);return;}newTurn(r);
}
function finishVisit(r){if(r.players.every(p=>p.done))r.phase='map';}
export function options(r){if(r.floor===TOTAL_FLOORS-1)return [{kind:'boss',name:'망각의 왕좌',desc:'최종 보스 · 두 개의 형상'}];if([2,5,8].includes(r.floor))return [{kind:'shop',name:'떠도는 상인',desc:'카드 · 유물 · 강화 · 덱 정리'},{kind:'rest',name:'달빛 쉼터',desc:'체력 회복 또는 카드 무료 강화'}];return [{kind:'battle',name:['잊힌 회랑','침묵의 숲','잠든 대성당'][r.floor%3],desc:'전투 · 골드와 직업 카드 보상'},{kind:[3,6,9].includes(r.floor)?'event':'elite',name:[3,6,9].includes(r.floor)?'기억의 우물':'봉인된 묘역',desc:[3,6,9].includes(r.floor)?'회복 · 골드 · 기억의 선물':'정예 전투 · 확정 유물 보상'}];}
function upgrade(p,index){if(!Number.isInteger(index)||!p.deck[index]||CARDS[p.deck[index]].upgraded)throw Error('강화할 기본 카드를 선택해주세요.');p.deck[index]+='+';}
export function act(r,p,a){if(!r.players.includes(p))throw Error('방에 참여해주세요.');const need=phase=>{if(r.phase!==phase)throw Error('지금은 할 수 없는 행동입니다.');};
 switch(a.type){
 case 'ready':need('lobby');p.ready=!p.ready;break;
 case 'start':need('lobby');if(p.id!==r.host)throw Error('방장만 시작할 수 있습니다.');if(!r.players.every(x=>x.ready))throw Error('모든 팀원이 준비해야 합니다.');r.phase='map';break;
 case 'route':{need('map');if(p.id!==r.host)throw Error('방장이 경로를 선택합니다.');const chosen=options(r).find(x=>x.kind===a.kind);if(!chosen)throw Error('선택할 수 없는 경로입니다.');r.floor++;r.history.push({floor:r.floor,...chosen});if(['battle','elite','boss'].includes(a.kind))battle(r,a.kind==='elite',a.kind==='boss');else{r.phase=a.kind;for(const x of r.players){x.done=false;x.bought=[];x.shop=offers(x,4);x.shopRelics=shuffle(Object.keys(RELICS).filter(key=>!has(x,key))).slice(0,2);}}break;}
 case 'play':{need('battle');if(p.ended||p.hp<=0)throw Error('다음 턴을 기다려주세요.');if(!Number.isInteger(a.index)||a.index<0||a.index>=p.hand.length)throw Error('카드를 다시 선택해주세요.');const id=p.hand[a.index],c=CARDS[id];if(a.card&&a.card!==id)throw Error('손패가 바뀌었습니다. 다시 선택해주세요.');if(p.energy<c.cost)throw Error('에너지가 부족합니다.');const v=preview(r,p,id),e=r.enemy;p.energy-=c.cost;if(c.allEnergy)p.energy=0;p.hand.splice(a.index,1);(c.exhaust?p.exhaust:p.discard).push(id);p.played++;p.metrics.cards++;
 let damage=0;const hits=[];if(c.damage)for(let i=0;i<v.hits&&e.hp>0;i++){const d=hitEnemy(e,v.damage);damage+=d;hits.push(d);}p.metrics.damage+=damage;
 for(const key of ['poison','burn','bleed','weak','vulnerable','frost'])e.status[key]+=c[key]||0;
 for(const key of ['strength','dexterity','thorns','regen','dodge','soul','channel','soulFlow','plating'])p.status[key]+=c[key]||0;
 let block=c.block?gainBlock(p,c.block):0;let healed=heal(p,v.heal+(c.lifesteal?damage:0));const allies=[];
 if(c.teamBlock||c.teamHeal)for(const ally of r.players)if(ally.hp>0){const b=c.teamBlock?gainBlock(ally,c.teamBlock):0;const h=heal(ally,c.teamHeal||0);allies.push({actor:ally.id,block:b,heal:h});}
 if(c.doublePoison)e.status.poison*=c.poisonMultiplier||2;if(c.retainBlock)p.retainBlock=true;if(c.selfDamage)p.hp=Math.max(1,p.hp-c.selfDamage);p.energy=Math.min(10,p.energy+(c.energy||0));if(has(p,'fang')&&p.played===3)healed+=heal(p,3);draw(p,c.draw||0);
 say(r,`${p.name} · ${c.name}${damage?` · ${damage} 피해`:''}`);emit(r,{type:'card',actor:p.id,card:id,fx:c.fx,damage,hits,block,heal:healed,allies,combo:v.combo,label:c.name});refreshEnemy(r);if(e.hp<=0)win(r);break;}
 case 'end':need('battle');if(p.ended)throw Error('이미 턴을 종료했습니다.');p.ended=true;if(r.players.every(x=>x.ended||x.hp<=0))resolve(r);break;
 case 'reward':need('reward');if(p.done)throw Error('이미 보상을 선택했습니다.');if(a.card!==null){if(!p.offers.includes(a.card))throw Error('선택할 수 없는 카드입니다.');p.deck.push(a.card);}p.done=true;finishVisit(r);break;
 case 'buy':{need('shop');if(p.done)throw Error('이미 상점을 나왔습니다.');let price;if(a.item==='heal')price=30;else if(a.item==='remove')price=45;else if(a.item==='upgrade')price=55;else if(p.shopRelics.includes(a.item))price=RELICS[a.item].price;else if(p.shop.includes(a.item))price=priceOf(a.item);else throw Error('없는 상품입니다.');if(p.bought.includes(a.item))throw Error('이미 구매했습니다.');if(p.gold<price)throw Error('골드가 부족합니다.');if(a.item==='heal'){if(p.hp===p.maxHp)throw Error('체력이 가득 찼습니다.');heal(p,25);}else if(a.item==='remove'){if(p.deck.length<=5||!Number.isInteger(a.index)||!p.deck[a.index])throw Error('덱에서 제거할 카드를 선택해주세요. (최소 5장)');p.deck.splice(a.index,1);}else if(a.item==='upgrade')upgrade(p,a.index);else if(p.shopRelics.includes(a.item))p.relics.push(a.item);else p.deck.push(a.item);p.gold-=price;p.bought.push(a.item);emit(r,{type:'purchase',actor:p.id,fx:'holy',label:'거래 완료'});break;}
 case 'leaveShop':need('shop');p.done=true;finishVisit(r);break;
 case 'rest':need('rest');if(p.done)throw Error('이미 쉬었습니다.');heal(p,Math.ceil(p.maxHp*.35)+(has(p,'feather')?15:0));p.done=true;finishVisit(r);break;
 case 'upgrade':need('rest');if(p.done)throw Error('이미 선택했습니다.');upgrade(p,a.index);p.done=true;finishVisit(r);break;
 case 'event':need('event');if(p.done)throw Error('이미 선택했습니다.');if(a.choice==='gold'){if(p.hp<=10)throw Error('체력이 부족합니다.');p.hp-=10;p.gold+=50;}else if(a.choice==='heal')heal(p,18);else if(a.choice==='card'){if(p.hp<=7)throw Error('체력이 부족합니다.');p.hp-=7;p.deck.push(offers(p,1)[0]+'+');}else throw Error('선택을 확인해주세요.');p.done=true;finishVisit(r);break;
 default:throw Error('알 수 없는 행동입니다.');
 }r.updated=Date.now();return r;
}
export function view(r,id){return {...r,options:options(r),players:r.players.map(p=>{const {pile,discard,hand,offers,shop,shopRelics,deck,exhaust,...rest}=p;return {...rest,online:Date.now()-p.lastSeen<15000,deckCount:deck.length,pileCount:pile?.length||0,discardCount:discard?.length||0,exhaustCount:exhaust?.length||0,...(p.id===id?{hand,offers,shop,shopRelics,deck,discard,exhaust,previews:hand?.map(key=>preview(r,p,key))}:{})};})};}
export function tick(r,now=Date.now()){if(r.phase==='lobby'){r.players=r.players.filter(p=>now-p.lastSeen<=45000);if(!r.players.some(p=>p.id===r.host))r.host=r.players[0]?.id;}if(r.phase==='battle'){for(const p of r.players)if(now-p.lastSeen>45000)p.ended=true;if(r.players.every(p=>p.ended||p.hp<=0))resolve(r);}if(['reward','shop','rest','event'].includes(r.phase)){for(const p of r.players)if(now-p.lastSeen>45000)p.done=true;finishVisit(r);}const host=r.players.find(p=>p.id===r.host);if(host&&now-host.lastSeen>45000){const next=r.players.find(p=>now-p.lastSeen<=45000);if(next)r.host=next.id;}}
